use_frameworks!

platform :ios, '8.0'

target 'PXXibPersonCatogeryKit_Example' do
  pod 'PXXibPersonCatogeryKit', :path => '../'

  target 'PXXibPersonCatogeryKit_Tests' do
    inherit! :search_paths

    
  end
end
